### ISSUE TITLE
Gitlab issue

### ISSUE THREAD

**Issue by mterzo** [voxpupuli/puppet_webhook#43]
My first execution of the web hook with gitlab, the initial clone / puppet file update takes longer than 10 seconds and gitlab webhook will fail on timeout.

According to the docs:
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#webhook-endpoint-tips

The next execution was super fast, nothing changed.

Every time I make changes to the puppet file or a new environment is added this may timeout.

Increasing the webhook timeout seems to be the only answer.
https://docs.gitlab.com/ee/user/project/integrations/webhooks.html#receiving-duplicate-or-multiple-web-hook-requests-triggered-by-one-event

Any other thoughts on this?

**Comment by alexjfisher** [comment]
It makes sense that the initial r10k run for a new environment takes much longer.  On the first run, all modules are downloaded.  When the environment is updated, only the modules with versions changed in the Puppetfile will have to be downloaded.

I don't use gitlab, so can't comment on the specifics of its webhook config.  I use bitbucket server.  It doesn't report on the return code of the hook.  Instead, I use slack notifications to report back to me whether the webhook was successful or not.

Ping @dhollinger .  You use gitlab, don't you?

**Comment by dhollinger** [comment]
@mterzo You shouldn't have to worry about timeout values on subsequent r10k environment deploys, but as @alexjfisher noted, the first environment deploy may take some time to complete.

We aren't specifying any specific timeout values within `puppet_webhook` and since we use Open3 calls on the backend to execute the r10k commands, we won't be able to report a success or failure back to Gitlab without waiting for the command to complete, so for the time being, it may be prudent to increase the webhook timeout value in Gitlab (For the record, I have seen this as well).

What we could do in the future is return a 200 to gitlab once the call makes it to the helper(s) in the Sinatra routes and then have users rely on Slack or another ChatOps tool/email to let them know if the deploy failed or not.

Thoughts?

**Comment by mterzo** [comment]
Using the "services" hook in gitlab wasn't allowing me to test all the config code before it gets pushed to the server.  I ended up using a simple shell wrapper calling the hook api to do a deployment using gitlab's concept of "environments".

Here's a sample.
```shell
curl -d '{"ref": "refs/heads/production", "branch": "production", "deleted": "false", "repository": { "name": "storage/aquari-puppet-config", "owner": { "login": "me" }}}'\
    -X POST \
    -H 'Accept: application/json' \
    -H 'Content-type: application/json' \
    -H 'X-GitHub-Event: push' \
    http://puppet:puppet@puppet-r10k/payload -vkq
```
The docs seem to be out of date, I had to provide "branch" in the json body and set the content-type.
